const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

const programs = [
  {
    title: "UWC",
    organization: "United World Colleges",
    category: "Scholarship",
    country: "Global",
    fundingType: "Full",
    level: "High School",
    deadline: new Date("2026-11-15"),
    shortDescription: "Two years of pre-university education at one of 18 UWC schools worldwide, fully funded.",
    fullDescription: "UWC selects students based on potential and merit, not ability to pay. Scholarships cover tuition, room, and board for the two-year IB Diploma program. Students from 150+ countries live and study together.",
    officialLink: "https://www.uwc.org",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "leadership,IB,diversity",
    featured: true,
  },
  {
    title: "Yale Young Global Scholars",
    organization: "Yale University",
    category: "Summer Program",
    country: "USA",
    fundingType: "Partial",
    level: "High School",
    deadline: new Date("2026-01-15"),
    shortDescription: "An academic summer program for outstanding high school students from around the world.",
    fullDescription: "YYGS brings together students for an intensive two-week academic program on Yale's campus. Sessions cover topics from science and policy to politics and the arts. Need-based financial aid available.",
    officialLink: "https://globalscholars.yale.edu",
    isRemote: "In-person",
    applicationFee: "Paid",
    eligibleCountries: "Global",
    tags: "STEM,policy,leadership",
    featured: true,
  },
  {
    title: "Diamond Challenge",
    organization: "University of Delaware",
    category: "Competition",
    country: "Global",
    fundingType: "Free",
    level: "High School",
    deadline: new Date("2026-11-12"),
    shortDescription: "A global entrepreneurship competition for high schoolers with $100,000 in prizes.",
    fullDescription: "Students form teams and submit either a business concept or a social innovation concept. Finalists pitch to judges. One of the largest pre-collegiate entrepreneurship competitions in the world.",
    officialLink: "https://diamondchallenge.org",
    isRemote: "Hybrid",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "entrepreneurship,business,pitch",
    featured: true,
  },
  {
    title: "Lumiere Research Scholar Program",
    organization: "Lumiere Education",
    category: "Research",
    country: "Online",
    fundingType: "Partial",
    level: "High School",
    deadline: new Date("2026-03-01"),
    shortDescription: "Conduct original research with a PhD mentor over 12 weeks, fully online.",
    fullDescription: "Students are paired one-on-one with a PhD mentor from a top university to produce an independent research paper in their area of interest. Financial aid available for qualifying students.",
    officialLink: "https://www.lumiere-education.com",
    isRemote: "Online",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "research,academic,writing",
    featured: false,
  },
  {
    title: "Global Citizen Year",
    organization: "Global Citizen Year",
    category: "Exchange",
    country: "Global",
    fundingType: "Partial",
    level: "High School",
    deadline: new Date("2026-02-01"),
    shortDescription: "A gap year program with immersive global experiences and leadership training.",
    fullDescription: "A bridge year between high school and college focused on global leadership, language immersion, and apprenticeships abroad. Need-based scholarships available.",
    officialLink: "https://www.globalcitizenyear.org",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "leadership,gap-year,culture",
    featured: false,
  },
  {
    title: "LaunchX",
    organization: "LaunchX",
    category: "Summer Program",
    country: "USA",
    fundingType: "Partial",
    level: "High School",
    deadline: new Date("2026-02-15"),
    shortDescription: "Build a real startup from scratch in an intensive entrepreneurship summer program.",
    fullDescription: "Students form teams, validate ideas, build products, and launch real companies. Includes mentorship from entrepreneurs and investors. Financial aid available.",
    officialLink: "https://launchx.com",
    isRemote: "Hybrid",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "entrepreneurship,startup,business",
    featured: true,
  },
  {
    title: "Coca-Cola Scholars Program",
    organization: "Coca-Cola Foundation",
    category: "Scholarship",
    country: "USA",
    fundingType: "Full",
    level: "High School",
    deadline: new Date("2026-10-01"),
    shortDescription: "A $20,000 scholarship for graduating high school seniors in the US.",
    fullDescription: "An achievement-based scholarship awarded to 150 students annually based on leadership, service, and academic excellence.",
    officialLink: "https://www.coca-colascholarsfoundation.org",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "USA",
    tags: "leadership,service,academic",
    featured: false,
  },
  {
    title: "TKS (The Knowledge Society)",
    organization: "TKS",
    category: "Summer Program",
    country: "Global",
    fundingType: "Paid",
    level: "High School",
    deadline: new Date("2026-05-31"),
    shortDescription: "A human accelerator developing teens to solve the world's biggest problems with emerging tech.",
    fullDescription: "TKS exposes students to emerging technologies like AI, biotech, and blockchain, developing mindsets and skills to create real-world impact.",
    officialLink: "https://www.tks.world",
    isRemote: "Hybrid",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "technology,AI,innovation",
    featured: false,
  },
  
  {
    title: "DAAD Scholarships",
    organization: "German Academic Exchange Service",
    category: "Scholarship",
    country: "Germany",
    fundingType: "Full",
    level: "Undergraduate",
    deadline: new Date("2026-10-15"),
    shortDescription: "Fully-funded scholarships to study in Germany for international students.",
    fullDescription: "DAAD offers a wide range of scholarships covering tuition, living costs, and travel for students from around the world to study at German universities.",
    officialLink: "https://www.daad.de",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "study-abroad,academic,europe",
    featured: true,
  },
  {
    title: "Hult Prize",
    organization: "Hult International Business School",
    category: "Competition",
    country: "Global",
    fundingType: "Free",
    level: "Undergraduate",
    deadline: new Date("2026-12-01"),
    shortDescription: "A global student competition with a $1 million prize for social entrepreneurship.",
    fullDescription: "Teams of students develop social enterprises to solve pressing global issues. The winning team receives $1 million in startup funding.",
    officialLink: "https://www.hultprize.org",
    isRemote: "Hybrid",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "entrepreneurship,social-impact,business",
    featured: false,
  },
  {
    title: "Future Minds Summit Thailand",
    organization: "Global Youth Network",
    category: "Summer Program",
    country: "Thailand",
    fundingType: "Partial",
    level: "Any",
    deadline: new Date("2026-06-15"),
    shortDescription: "A global youth summit in Bangkok bringing together changemakers and innovators.",
    fullDescription: "The Future Minds Summit gathers young leaders in Bangkok for workshops, networking, and collaboration on global challenges. Held 16-19 July 2026.",
    officialLink: "https://thegyn.org/fms-thailand/",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "leadership,youth,networking",
    featured: false,
  },
  {
    title: "Civic Youth Forum 2026",
    organization: "The CDA",
    category: "Competition",
    country: "Denmark",
    fundingType: "Partial",
    level: "Any",
    deadline: new Date("2026-07-05"),
    shortDescription: "A civic engagement forum for young leaders in Copenhagen.",
    fullDescription: "The Civic Youth Forum brings together young people passionate about democracy and civic action in Copenhagen, 17-20 September 2026, for dialogue, workshops, and collaboration.",
    officialLink: "https://thecda.co/civic-youth-forum-2026/#register",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "civic,democracy,leadership",
    featured: false,
  },
  {
    title: "Youth Democracy Summit 2026",
    organization: "The CIPS",
    category: "Competition",
    country: "Italy",
    fundingType: "Partial",
    level: "Any",
    deadline: new Date("2026-08-10"),
    shortDescription: "A summit on democracy and youth leadership held in Rome.",
    fullDescription: "The Youth Democracy Summit convenes young leaders in Rome, 1-4 October 2026, to discuss democratic values, civic participation, and global cooperation.",
    officialLink: "https://thecips.org/yds2026/ref/10/",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "democracy,civic,youth",
    featured: false,
  },
  {
    title: "AYFN Autumn Japan Culture Camp 2026",
    organization: "Asian Youth Friendship Network",
    category: "Exchange",
    country: "Japan",
    fundingType: "Full",
    level: "Any",
    deadline: new Date("2026-07-15"),
    shortDescription: "Fully-funded cultural exchange camp in Osaka, Japan.",
    fullDescription: "A fully-funded cultural immersion program in Osaka, 15-20 November 2026, offering participants the chance to experience Japanese culture, build cross-cultural friendships, and develop global perspective.",
    officialLink: "https://ayfnhq.org/event/scholarship-opportunity-autumn-japan-culture-camp-2025/",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "culture,exchange,japan,fully-funded",
    featured: true,
  },
  {
    title: "Zayed Sustainability Prize",
    organization: "Government of UAE",
    category: "Competition",
    country: "UAE",
    fundingType: "Free",
    level: "Any",
    deadline: new Date("2026-06-22"),
    shortDescription: "A global award recognizing sustainability solutions, including a Global High Schools category.",
    fullDescription: "The Zayed Sustainability Prize awards organizations and schools driving impact in health, food, energy, water, and climate action. The Global High Schools category funds student-led sustainability projects worldwide.",
    officialLink: "https://zayedsustainabilityprize.com/en/",
    isRemote: "Hybrid",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "sustainability,climate,impact",
    featured: true,
  },
  {
    title: "Liberty Prize",
    organization: "Liberty Prize",
    category: "Competition",
    country: "Global",
    fundingType: "Free",
    level: "Any",
    deadline: new Date("2026-06-30"),
    shortDescription: "An international competition recognizing ideas and projects advancing liberty.",
    fullDescription: "The Liberty Prize invites students and young thinkers worldwide to submit essays and projects exploring freedom, rights, and civic values, with recognition and awards for standout entries.",
    officialLink: "https://www.libertyprize.org/#introduction",
    isRemote: "Online",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "civic,writing,liberty",
    featured: false,
  },
  {
    title: "WikiSfera Camp Season 2",
    organization: "WikiMarafon",
    category: "Summer Program",
    country: "Uzbekistan",
    fundingType: "Free",
    level: "Any",
    deadline: new Date("2026-06-20"),
    shortDescription: "A camp to improve Uzbek Wikipedia and grow Uzbek-language content online.",
    fullDescription: "Part of the WikiMarafon project, this camp in Bostanliq, Tashkent region, teaches participants to create and edit Wikipedia articles, analyze information, and build editing skills, all aimed at expanding quality Uzbek-language content online.",
    officialLink: "https://t.me/wikitanlov_bot",
    isRemote: "In-person",
    applicationFee: "Free",
    eligibleCountries: "Uzbekistan",
    tags: "writing,editing,wikipedia,uzbek",
    featured: false,
  },
  {
    title: "NextGen Innovators Challenge '26",
    organization: "NextGen Innovators",
    category: "Competition",
    country: "Global",
    fundingType: "Free",
    level: "Any",
    deadline: new Date("2026-08-31"),
    shortDescription: "A global student competition for tech-driven solutions to environmental challenges.",
    fullDescription: "This year's theme is Environmental Transformation Through Technology. Students worldwide submit innovative ideas in clean energy, climate action, sustainable cities, medical technology, and education access. Open to all students, no application fee.",
    officialLink: "https://nextgeninnovatorschallenge.org/",
    isRemote: "Online",
    applicationFee: "Free",
    eligibleCountries: "Global",
    tags: "technology,climate,innovation",
    featured: true,
  },
  {
    title: "Global Youth Impact Summit '26",
    organization: "Council for Global Affairs and Development",
    category: "Summer Program",
    country: "Europe",
    fundingType: "Partial",
    level: "Any",
    deadline: new Date("2026-07-01"),
    shortDescription: "A four-day international youth leadership summit, no IELTS/TOEFL required.",
    fullDescription: "Brings together young leaders, changemakers, students, entrepreneurs, and innovators for a four-day experience focused on leadership, sustainable development, innovation, and cultural exchange in one of Europe's most vibrant historic cities. Open to ages 15+; applicants can apply without IELTS/TOEFL.",
    officialLink: "https://thecgad.org/gyis-2026/ref/464/",
    isRemote: "In-person",
    applicationFee: "Paid",
    eligibleCountries: "Global",
    tags: "leadership,youth,networking",
    featured: false,
  },
];

async function main() {
  console.log("Seeding programs...");
  for (const p of programs) {
    await prisma.program.create({ data: p });
    console.log(`  Added: ${p.title}`);
  }
  console.log(`Done. Seeded ${programs.length} programs.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });